version: "3"

services:
  front:
    container_name: front
    build:
      context: ./
      dockerfile: Dockerfile

    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
